version: '3'

networks:
  gecko:
    driver: bridge

services:

################################
# Setup node container
################################
  server:
    build: ./
    expose:
      - ${GECKO_SERVER_HOST_PORT}
    environment:
      GECKO_SERVER_PORT: ${GECKO_SERVER_HOST_PORT}
      GECKO_SERVER_CONTAINER_PORT: ${GECKO_SERVER_CONTAINER_PORT}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_COGNITO_POOL: ${AWS_COGNITO_POOL}
      AWS_FOLDER: ${AWS_FOLDER}
      GECKO_APP_HOST: ${GECKO_APP_HOST}
    networks:
      - gecko
    ports:
      - ${GECKO_SERVER_HOST_PORT}:${GECKO_SERVER_CONTAINER_PORT}
    command: npm run server